declare module 'vue' {
  export interface GlobalComponents {
    VBody: typeof import('@vima-tech/ui-admin')['VBody']
    VButton: typeof import('@vima-tech/ui-admin')['VButton']
    VButtonGroup: typeof import('@vima-tech/ui-admin')['VButtonGroup']
    VCard: typeof import('@vima-tech/ui-admin')['VCard']
    VCol: typeof import('@vima-tech/ui-admin')['VCol']
    VCollapse: typeof import('@vima-tech/ui-admin')['VCollapse']
    VCollapseItem: typeof import('@vima-tech/ui-admin')['VCollapseItem']
    VContainer: typeof import('@vima-tech/ui-admin')['VContainer']
    VCountdown: typeof import('@vima-tech/ui-admin')['VCountdown']
    VDatePicker: typeof import('@vima-tech/ui-admin')['VDatePicker']
    VDescriptions: typeof import('@vima-tech/ui-admin')['VDescriptions']
    VDescriptionsItem: typeof import('@vima-tech/ui-admin')['VDescriptionsItem']
    VDivider: typeof import('@vima-tech/ui-admin')['VDivider']
    VDropdown: typeof import('@vima-tech/ui-admin')['VDropdown']
    VDropdownMenu: typeof import('@vima-tech/ui-admin')['VDropdownMenu']
    VDropdownMenuItem: typeof import('@vima-tech/ui-admin')['VDropdownMenuItem']
    VForm: typeof import('@vima-tech/ui-admin')['VForm']
    VFormItem: typeof import('@vima-tech/ui-admin')['VFormItem']
    VFullscreen: typeof import('@vima-tech/ui-admin')['VFullscreen']
    VHeader: typeof import('@vima-tech/ui-admin')['VHeader']
    VIcon: typeof import('@vima-tech/ui-admin')['VIcon']
    VInput: typeof import('@vima-tech/ui-admin')['VInput']
    VInputNumber: typeof import('@vima-tech/ui-admin')['VInputNumber']
    VLayer: typeof import('@vima-tech/ui-admin')['VLayer']
    VLayout: typeof import('@vima-tech/ui-admin')['VLayout']
    VLoading: typeof import('@vima-tech/ui-admin')['VLoading']
    VProgress: typeof import('@vima-tech/ui-admin')['VProgress']
    VRadio: typeof import('@vima-tech/ui-admin')['VRadio']
    VRadioGroup: typeof import('@vima-tech/ui-admin')['VRadioGroup']
    VRow: typeof import('@vima-tech/ui-admin')['VRow']
    VSelect: typeof import('@vima-tech/ui-admin')['VSelect']
    VSelectOption: typeof import('@vima-tech/ui-admin')['VSelectOption']
    VSide: typeof import('@vima-tech/ui-admin')['VSide']
    VSkeleton: typeof import('@vima-tech/ui-admin')['VSkeleton']
    VSwitch: typeof import('@vima-tech/ui-admin')['VSwitch']
    VTab: typeof import('@vima-tech/ui-admin')['VTab']
    VTabItem: typeof import('@vima-tech/ui-admin')['VTabItem']
    VTable: typeof import('@vima-tech/ui-admin')['VTable']
    VTag: typeof import('@vima-tech/ui-admin')['VTag']
    VTagInput: typeof import('@vima-tech/ui-admin')['VTagInput']
    VTextarea: typeof import('@vima-tech/ui-admin')['VTextarea']
    VTree: typeof import('@vima-tech/ui-admin')['VTree']
    VUpload: typeof import('@vima-tech/ui-admin')['VUpload']
    VColumnSetting: typeof import('@vima-tech/ui-admin')['VColumnSetting']
  }
}

export {}
