// 生成自 vendor/vima-ui-admin/dist/ai-manifest.json（0.1.0），勿手改；
// 由 vima-cli 仓库 scripts/gen-from-manifest.mjs 重新生成（同源防漂移，评估 §6A5）。
// 组件库 install() 已全局注册全部组件（main.ts app.use），本声明为模板中的
// 全局组件提供类型与 IDE 补全。
declare module 'vue' {
  export interface GlobalComponents {
    VAlert: typeof import('@vima-tech/ui-admin')['VAlert']
    VAvatar: typeof import('@vima-tech/ui-admin')['VAvatar']
    VAvatarGroup: typeof import('@vima-tech/ui-admin')['VAvatarGroup']
    VBadge: typeof import('@vima-tech/ui-admin')['VBadge']
    VBody: typeof import('@vima-tech/ui-admin')['VBody']
    VBreadcrumb: typeof import('@vima-tech/ui-admin')['VBreadcrumb']
    VBreadcrumbItem: typeof import('@vima-tech/ui-admin')['VBreadcrumbItem']
    VButton: typeof import('@vima-tech/ui-admin')['VButton']
    VButtonGroup: typeof import('@vima-tech/ui-admin')['VButtonGroup']
    VCard: typeof import('@vima-tech/ui-admin')['VCard']
    VCheckbox: typeof import('@vima-tech/ui-admin')['VCheckbox']
    VCheckboxGroup: typeof import('@vima-tech/ui-admin')['VCheckboxGroup']
    VCol: typeof import('@vima-tech/ui-admin')['VCol']
    VCollapse: typeof import('@vima-tech/ui-admin')['VCollapse']
    VCollapseItem: typeof import('@vima-tech/ui-admin')['VCollapseItem']
    VColumnSetting: typeof import('@vima-tech/ui-admin')['VColumnSetting']
    VContainer: typeof import('@vima-tech/ui-admin')['VContainer']
    VCountdown: typeof import('@vima-tech/ui-admin')['VCountdown']
    VDatePicker: typeof import('@vima-tech/ui-admin')['VDatePicker']
    VDescriptions: typeof import('@vima-tech/ui-admin')['VDescriptions']
    VDescriptionsItem: typeof import('@vima-tech/ui-admin')['VDescriptionsItem']
    VDivider: typeof import('@vima-tech/ui-admin')['VDivider']
    VDrawer: typeof import('@vima-tech/ui-admin')['VDrawer']
    VDropdown: typeof import('@vima-tech/ui-admin')['VDropdown']
    VDropdownMenu: typeof import('@vima-tech/ui-admin')['VDropdownMenu']
    VDropdownMenuItem: typeof import('@vima-tech/ui-admin')['VDropdownMenuItem']
    VEmpty: typeof import('@vima-tech/ui-admin')['VEmpty']
    VForm: typeof import('@vima-tech/ui-admin')['VForm']
    VFormItem: typeof import('@vima-tech/ui-admin')['VFormItem']
    VFullscreen: typeof import('@vima-tech/ui-admin')['VFullscreen']
    VHeader: typeof import('@vima-tech/ui-admin')['VHeader']
    VIcon: typeof import('@vima-tech/ui-admin')['VIcon']
    VInput: typeof import('@vima-tech/ui-admin')['VInput']
    VInputNumber: typeof import('@vima-tech/ui-admin')['VInputNumber']
    VLayer: typeof import('@vima-tech/ui-admin')['VLayer']
    VLayout: typeof import('@vima-tech/ui-admin')['VLayout']
    VLink: typeof import('@vima-tech/ui-admin')['VLink']
    VLoading: typeof import('@vima-tech/ui-admin')['VLoading']
    VPagination: typeof import('@vima-tech/ui-admin')['VPagination']
    VPopover: typeof import('@vima-tech/ui-admin')['VPopover']
    VProgress: typeof import('@vima-tech/ui-admin')['VProgress']
    VRadio: typeof import('@vima-tech/ui-admin')['VRadio']
    VRadioGroup: typeof import('@vima-tech/ui-admin')['VRadioGroup']
    VRow: typeof import('@vima-tech/ui-admin')['VRow']
    VSelect: typeof import('@vima-tech/ui-admin')['VSelect']
    VSelectOption: typeof import('@vima-tech/ui-admin')['VSelectOption']
    VSide: typeof import('@vima-tech/ui-admin')['VSide']
    VSkeleton: typeof import('@vima-tech/ui-admin')['VSkeleton']
    VStatistic: typeof import('@vima-tech/ui-admin')['VStatistic']
    VStep: typeof import('@vima-tech/ui-admin')['VStep']
    VSteps: typeof import('@vima-tech/ui-admin')['VSteps']
    VSwitch: typeof import('@vima-tech/ui-admin')['VSwitch']
    VTab: typeof import('@vima-tech/ui-admin')['VTab']
    VTabItem: typeof import('@vima-tech/ui-admin')['VTabItem']
    VTable: typeof import('@vima-tech/ui-admin')['VTable']
    VTag: typeof import('@vima-tech/ui-admin')['VTag']
    VTagInput: typeof import('@vima-tech/ui-admin')['VTagInput']
    VTemplateEditor: typeof import('@vima-tech/ui-admin')['VTemplateEditor']
    VTextarea: typeof import('@vima-tech/ui-admin')['VTextarea']
    VTimePicker: typeof import('@vima-tech/ui-admin')['VTimePicker']
    VTooltip: typeof import('@vima-tech/ui-admin')['VTooltip']
    VTree: typeof import('@vima-tech/ui-admin')['VTree']
    VUpload: typeof import('@vima-tech/ui-admin')['VUpload']
  }
}

export {}
