// C2 单测：vima sync 状态重建（设计 §19.8）
import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { mkdtemp, cp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import os from 'node:os';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const BIN = path.join(HERE, '..', '..', 'bin', 'vima.mjs');
const GOLDEN = path.join(HERE, '..', 'fixtures', 'golden');
const MARKER = '<!-- generated by vima sync — 手改无效，以任务 frontmatter 为准 -->';
const TASK_IDS = ['shared-base', 'device-api-be', 'device-list-fe', 'full-test'];

function runCli(cwd, args) {
  return spawnSync(process.execPath, [BIN, ...args], { cwd, encoding: 'utf8' });
}

async function makeGoldenCopy(t) {
  const tmp = await mkdtemp(path.join(os.tmpdir(), 'vima-c2-sync-'));
  t.after(async () => rm(tmp, { recursive: true, force: true }));
  await cp(GOLDEN, tmp, { recursive: true });
  return tmp;
}

/** 把 lifecycle.taskStats 改坏，制造需要 sync 重建的现场。 */
async function corruptStats(tmp) {
  const p = path.join(tmp, 'docs', 'lifecycle.json');
  const lifecycle = JSON.parse(await readFile(p, 'utf8'));
  lifecycle.taskStats = { total: 9, done: 3, failed: 2, blocked: 1, updatedAt: '2026-01-01T00:00:00Z' };
  await writeFile(p, JSON.stringify(lifecycle, null, 2));
}

test('sync：重建 taskStats{total:4,done:1} 并生成带标记的 README', async (t) => {
  const tmp = await makeGoldenCopy(t);
  await corruptStats(tmp);

  const proc = runCli(tmp, ['sync']);
  assert.equal(proc.status, 0, `stderr: ${proc.stderr}`);

  // taskStats 以 frontmatter 为准重建
  const lifecycle = JSON.parse(readFileSync(path.join(tmp, 'docs', 'lifecycle.json'), 'utf8'));
  assert.equal(lifecycle.taskStats.total, 4);
  assert.equal(lifecycle.taskStats.done, 1);
  assert.equal(lifecycle.taskStats.failed, 0);
  assert.equal(lifecycle.taskStats.blocked, 0);
  assert.equal(typeof lifecycle.taskStats.updatedAt, 'string');

  // README：首行生成标记 + 全部 4 个 taskId + 批次视图
  const readme = readFileSync(path.join(tmp, 'docs', 'tasks', 'README.md'), 'utf8');
  assert.equal(readme.split('\n')[0], MARKER);
  for (const id of TASK_IDS) assert.ok(readme.includes(id), `README 应含 ${id}`);
  assert.match(readme, /## 批次视图/);
  assert.match(readme, /- \[x\] shared-base/); // done 任务打勾
});

test('sync：幂等——连续两次运行 README 字节一致', async (t) => {
  const tmp = await makeGoldenCopy(t);
  runCli(tmp, ['sync']);
  const first = readFileSync(path.join(tmp, 'docs', 'tasks', 'README.md'), 'utf8');
  const proc = runCli(tmp, ['sync']);
  assert.equal(proc.status, 0);
  assert.match(proc.stdout, /README\.md 无变化/);
  const second = readFileSync(path.join(tmp, 'docs', 'tasks', 'README.md'), 'utf8');
  assert.equal(first, second);
});

test('sync --dry-run：只打印变更，不写盘', async (t) => {
  const tmp = await makeGoldenCopy(t);
  await corruptStats(tmp);

  const proc = runCli(tmp, ['sync', '--dry-run']);
  assert.equal(proc.status, 0, `stderr: ${proc.stderr}`);
  assert.match(proc.stdout, /dry-run/);
  assert.match(proc.stdout, /重建 taskStats/);

  // lifecycle 保持坏值未被修改
  const lifecycle = JSON.parse(readFileSync(path.join(tmp, 'docs', 'lifecycle.json'), 'utf8'));
  assert.equal(lifecycle.taskStats.done, 3);
  // README 未生成
  assert.equal(existsSync(path.join(tmp, 'docs', 'tasks', 'README.md')), false);
});

test('sync：清理过期 shared-write-token，保留未过期令牌', async (t) => {
  const tmp = await makeGoldenCopy(t);
  const tokenPath = path.join(tmp, '.vima', 'shared-write-token');
  await mkdir(path.dirname(tokenPath), { recursive: true });

  // 过期令牌 → 删除
  await writeFile(tokenPath, '2020-01-01T00:00:00Z\n');
  let proc = runCli(tmp, ['sync']);
  assert.equal(proc.status, 0);
  assert.match(proc.stdout, /清理过期写令牌/);
  assert.equal(existsSync(tokenPath), false);

  // 未过期令牌 → 保留
  await writeFile(tokenPath, '2099-01-01T00:00:00Z\n');
  proc = runCli(tmp, ['sync']);
  assert.equal(proc.status, 0);
  assert.equal(existsSync(tokenPath), true);
});

test('sync：缺 lifecycle.json → exit 4', async (t) => {
  const tmp = await mkdtemp(path.join(os.tmpdir(), 'vima-c2-sync-'));
  t.after(async () => rm(tmp, { recursive: true, force: true }));
  await cp(path.join(GOLDEN, 'docs', 'tasks'), path.join(tmp, 'docs', 'tasks'), { recursive: true });

  const proc = runCli(tmp, ['sync']);
  assert.equal(proc.status, 4);
  assert.match(proc.stderr, /lifecycle/);
});
