// vima sync —— 确定性状态重建（设计 §19.8 / §9.6）：
//   frontmatter → lifecycle.taskStats + docs/tasks/README.md（人可读视图）+ 清理过期写令牌。
import path from 'node:path';
import { parseArgs } from 'node:util';
import { readFile, unlink } from 'node:fs/promises';
import { loadTasks } from '../model/tasks.mjs';
import { loadLifecycle, saveLifecycle } from '../model/lifecycle.mjs';
import { atomicWriteFile, fileExists } from '../util/fs.mjs';
import { EXIT, usageFromParseArgs } from '../util/errors.mjs';
import { computeBatches } from './plan.mjs';

const README_MARKER = '<!-- generated by vima sync — 手改无效，以任务 frontmatter 为准 -->';
const README_REL = 'docs/tasks/README.md';
const TOKEN_REL = '.vima/shared-write-token';

/** markdown 表格单元格转义（管道符）与空值占位。 */
function cell(v) {
  const s = v === undefined || v === null || v === '' ? '—' : String(v);
  return s.replaceAll('|', '\\|');
}

/**
 * 从任务 frontmatter 生成 docs/tasks/README.md 全文（确定性，无时间戳）。
 * 首行固定生成标记；含任务总表 + computeBatches 批次视图。
 */
export function renderReadme(tasks, batches) {
  const byId = new Map(tasks.map((t) => [t.id, t]));
  const lines = [README_MARKER, '', '# 任务清单（自动生成视图）', ''];
  lines.push('> 本文件由 `vima sync` 从 docs/tasks/*.md 的 frontmatter 生成，仅供人读，不参与调度决策。');
  lines.push('');

  // A16：任何任务带 app 字段（多端项目）时任务总表加「端」列；单端项目输出零变化
  const hasApp = tasks.some((t) => typeof t.fm.app === 'string' && t.fm.app !== '');
  lines.push('## 任务总表', '');
  lines.push(hasApp
    ? '| taskId | title | status | layer | 端 | dependsOn | contract |'
    : '| taskId | title | status | layer | dependsOn | contract |');
  lines.push(hasApp ? '| --- | --- | --- | --- | --- | --- | --- |' : '| --- | --- | --- | --- | --- | --- |');
  for (const t of [...tasks].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
    const appCol = hasApp ? `| ${cell(t.fm.app ?? '—')} ` : '';
    lines.push(
      `| ${cell(t.id)} | ${cell(t.fm.title)} | ${cell(t.fm.status)} | ${cell(t.fm.layer)} ` +
        `${appCol}| ${cell(t.fm.dependsOn.join('、'))} | ${cell(t.fm.contract)} |`
    );
  }
  lines.push('');

  lines.push('## 批次视图', '');
  for (const b of batches) {
    lines.push(`### 批次 ${b.index}（${b.layer}，${b.mode === 'parallel' ? '并行' : '串行'}）`, '');
    for (const id of b.tasks) {
      const t = byId.get(id);
      const box = t.fm.status === 'done' ? 'x' : ' ';
      const app = hasApp && typeof t.fm.app === 'string' && t.fm.app !== '' ? `［${t.fm.app}］` : '';
      const deps = t.fm.dependsOn.length > 0 ? `（依赖：${t.fm.dependsOn.join('、')}）` : '';
      lines.push(`- [${box}] ${id}：${app}${t.fm.title}${deps}`);
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

/** 从任务清单重算 lifecycle.taskStats 的四个计数（internal-contracts §6.2）。 */
export function countTaskStats(tasks) {
  const stats = { total: tasks.length, done: 0, failed: 0, blocked: 0 };
  for (const t of tasks) {
    if (t.fm.status === 'done') stats.done += 1;
    else if (t.fm.status === 'failed') stats.failed += 1;
    else if (t.fm.status === 'blocked') stats.blocked += 1;
  }
  return stats;
}

export async function run(argv, ctx) {
  let values;
  try {
    ({ values } = parseArgs({
      args: argv,
      options: { 'dry-run': { type: 'boolean', default: false } },
      allowPositionals: true,
    }));
  } catch (err) {
    throw usageFromParseArgs(err);
  }
  const dryRun = values['dry-run'];
  const root = ctx.cwd;

  const lifecycle = await loadLifecycle(root); // 缺失 → VimaError('NO_LIFECYCLE', exit 4)
  const tasks = await loadTasks(root);
  const batches = computeBatches(tasks); // 缺依赖/成环 → exit 2（视图不能建立在坏图上）

  const lines = [];
  const prefix = dryRun ? '（dry-run）' : '';

  // ── 1. 重建 taskStats ─────────────────────────────────────────────────────
  const next = countTaskStats(tasks);
  const cur = lifecycle.taskStats ?? {};
  const statsChanged = ['total', 'done', 'failed', 'blocked'].some((k) => cur[k] !== next[k]);
  if (statsChanged) {
    const diff = ['total', 'done', 'failed', 'blocked']
      .filter((k) => cur[k] !== next[k])
      .map((k) => `${k}: ${cur[k] ?? '?'} → ${next[k]}`)
      .join('，');
    lines.push(`${prefix}🔁 重建 taskStats：${diff}`);
    if (!dryRun) {
      lifecycle.taskStats = { ...next, updatedAt: new Date().toISOString() };
      await saveLifecycle(root, lifecycle);
    }
  } else {
    lines.push(`✅ taskStats 已一致（total: ${next.total}，done: ${next.done}，failed: ${next.failed}，blocked: ${next.blocked}）`);
  }

  // ── 2. 重生成 docs/tasks/README.md ───────────────────────────────────────
  const readmePath = path.join(root, README_REL);
  const content = renderReadme(tasks, batches);
  let old = null;
  if (await fileExists(readmePath)) old = await readFile(readmePath, 'utf8');
  if (old === content) {
    lines.push(`✅ ${README_REL} 无变化`);
  } else {
    lines.push(`${prefix}📝 ${old === null ? '生成' : '重生成'} ${README_REL}（${tasks.length} 个任务 / ${batches.length} 个批次）`);
    if (!dryRun) await atomicWriteFile(readmePath, content);
  }

  // ── 3. 清理过期的 .vima/shared-write-token ───────────────────────────────
  const tokenPath = path.join(root, TOKEN_REL);
  if (await fileExists(tokenPath)) {
    const raw = (await readFile(tokenPath, 'utf8')).trim();
    const expiry = Date.parse(raw);
    if (!Number.isNaN(expiry) && expiry < Date.now()) {
      lines.push(`${prefix}🧹 清理过期写令牌 ${TOKEN_REL}（过期于 ${raw}）`);
      if (!dryRun) await unlink(tokenPath);
    } else if (Number.isNaN(expiry)) {
      lines.push(`⚠️ ${TOKEN_REL} 内容不是 ISO 时刻（"${raw}"），保留不动`);
    } else {
      lines.push(`✅ 写令牌有效（过期于 ${raw}），保留`);
    }
  }

  if (dryRun) lines.push('ℹ️ dry-run 预览结束，未写入任何文件');
  process.stdout.write(`${lines.join('\n')}\n`);
  return EXIT.OK;
}
